import { cn } from "@/lib/utils";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { fontSans } from "@/lib/fonts";
import { SiteHeader } from "@/components/Header/SiteHeader";
import { TailwindIndicator } from "@/components/Tailwind/TailwindIndicator";
import { ThemeProvider } from "@/components/Theme/ThemeProvider";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <html lang="es" suppressHydrationWarning>
        <head>
          {/* <Script
            src="/lib/orb.js"
            strategy="beforeInteractive"
          /> */}
        </head>
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable
          )}
        >
          {/* <ThemeProvider attribute="class" defaultTheme="system" enableSystem> */}
          {/* <AuthProvider> */}
          <div className="relative flex min-h-screen flex-col">
            <SiteHeader />
            <div className="flex-1">{children}</div>
            {/* <SiteFooter /> */}
          </div>
          {/* </AuthProvider> */}
          <TailwindIndicator />
          {/* </ThemeProvider> */}
        </body>
      </html>
    </>
  );
}
